apiVersion: v1
kind: Service
metadata:
  name: thapim-portal
  labels:
    app: thapim-portal
spec:
  selector:
    app: thapim-portal
  ports:
    - protocol: TCP
      name: portal
      port: 80
      nodePort: 31000
      targetPort: 80
  type: NodePort
  externalTrafficPolicy: Local
