apiVersion: v1
kind: Service
metadata:
  name: thapim-mariadb
spec:
  selector:
    app: thapim-mariadb
  ports:
    - protocol: TCP
      name: mariadb
      port: 3306
      targetPort: 3306
  type: ClusterIP
