apiVersion: apps/v1
kind: Deployment
metadata:
  name: thapim-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thapim-portal
  template:
    metadata:
      labels:
        app: thapim-portal
    spec:
      containers:
      - name: app
        image: 004537899190.dkr.ecr.eu-west-1.amazonaws.com/thapimv3.8:v3.8R_PORTAL_WITH_JAVA_THREE
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: portal
        - secretRef:
            name: portal-prop
#        resources:
 #           requests:
  #            cpu: 4000m
   #           memory: 8Gi
    #          ephemeral-storage: 100Gi
     #       limits:
      #        cpu: 4000m
       #       memory: 8Gi
        #      ephemeral-storage: 100Gi
      imagePullSecrets:
      - name: thapim1
