apiVersion: v1
kind: Service
metadata:
  name: thapim-keycloak
  labels:
    app: thapim-keycloak
spec:
  selector:
    app: thapim-keycloak
  ports:
    - protocol: TCP
      name: portal
      port: 8080
      nodePort: 31100
      targetPort: 8080
  type: NodePort
  externalTrafficPolicy: Local